name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Menjadwalkan workflow untuk berjalan setiap 6 jam

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360  # Set the maximum runtime to 6 hours

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Authenticate Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP in the registry
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Write-Host "RDP Enabled in the registry"

    - name: Enable RDP in the firewall
      run: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Host "RDP rule enabled in the firewall"

    - name: Set RDP User Authentication
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Write-Host "RDP user authentication set"

    - name: Set Password for runneradmin
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Write-Host "Password for runneradmin set"

    - name: Start Ngrok Tunnel
      run: |
        .\ngrok\ngrok.exe tcp 3389 --log=stdout
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
